name: vault

on:
  push:
  pull_request:

jobs:
  jbang:
    name: Run Vault tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup JBang
        uses: jbangdev/setup-jbang@v0.1.1
      - name: Run test
        run: |
          jbang vault/vaultTest.java
